### ISSUE TITLE
SM tools download is broken

### ISSUE THREAD

**Issue by nerdynomadd** [digicert/ssm-code-signing#19]
Hello, since the latest release of smtools this morning, the download of the smtools-windows-x64.msi is broken with the following error:

```
Tool to be downloaded and used {} and url is {} smtools-windows-x64.msi signingmanager/api-ui/v1/releases/noauth/smtools-windows-x64.msi/download
##vso[task.debug]APIKey=undefined

error when executing setup task of STM Error: Request failed with status code 400
    at createError (D:\a\_actions\digicert\ssm-code-signing\v0.0.2\build\index.js:5657:15)
    at settle (D:\a\_actions\digicert\ssm-code-signing\v0.0.2\build\index.js:5919:12)
    at IncomingMessage.handleStreamEnd (D:\a\_actions\digicert\ssm-code-signing\v0.0.2\build\index.js:4959:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
```

**Comment by floitsch** [comment]
And here is the output for the Linux version:
```
Tool to be downloaded and used {} and url is {} smtools-linux-x64.zip signingmanager/api-ui/v1/releases/noauth/smtools-linux-x64.zip/download
##vso[task.debug]APIKey=undefined

error when executing setup task of STM Error: Request failed with status code 400
    at createError (/home/runner/work/_actions/digicert/ssm-code-signing/v0.0.2/build/index.js:5657:15)
    at settle (/home/runner/work/_actions/digicert/ssm-code-signing/v0.0.2/build/index.js:5919:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/digicert/ssm-code-signing/v0.0.2/build/index.js:4959:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    url: 'https://demo.one.digicert.com/signingmanager/api-ui/v1/releases/noauth/smtools-linux-x64.zip/download',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'x-api-key': '***',
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'x-api-key': [Array],
      'user-agent': [Array],
      host: [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      date: 'Thu, 08 Feb 2024 12:08:31 GMT',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'x-envoy-upstream-service-time': '19',
      'strict-transport-security': 'max-age=15724800; includeSubDomains',
      'x-xss-protection': '1; mode=block',
      'x-frame-options': 'same-origin',
      'x-content-type-options': 'nosniff',
      'content-security-policy': "default-src 'self' dctrustassistant: http://localhost:*/ http://127.0.0.1:*/ https://127.0.0.1:*/ https://assets.adobedtm.com/ https://*.pendo.io/  https://www.googletagmanager.com/  https://www.google-analytics.com/ https://purecatamphetamine.github.io https://*.fullstory.com/ https://*.digicert.com/ https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.12.313/pdf.worker.js https://*.storage.googleapis.com/ https://services.nvd.nist.gov blob: data: 'unsafe-inline' 'unsafe-eval';"
    },
    config: {
      url: 'https://demo.one.digicert.com/signingmanager/api-ui/v1/releases/noauth/smtools-linux-x64.zip/download',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'arraybuffer',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /signingmanager/api-ui/v1/releases/noauth/smtools-linux-x64.zip/download HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'x-api-key: ***\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: demo.one.digicert.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/signingmanager/api-ui/v1/releases/noauth/smtools-linux-x64.zip/download',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'demo.one.digicert.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    data: <Buffer 7b 22 65 72 72 6f 72 22 3a 7b 22 73 74 61 74 75 73 22 3a 22 69 6e 76 61 6c 69 64 5f 64 61 74 61 22 2c 22 6d 65 73 73 61 67 65 22 3a 22 50 72 6f 76 69 ... 24 more bytes>
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by puni9869** [comment]
Facing the same issue in signing the windows binary.

**Comment by floitsch** [comment]
I have chatted with their support. (Not sure why they don't answer here). At least they are aware of the issue.

In the meantime, I could work around the issue by installing the smtools by hand before using this action:

```
      - name: Install smtools
        shell: cmd
        env:
          SM_API_KEY: ${{ env.SECRET_API_KEY }}
        run: |
          curl -X GET  https://one.digicert.com/signingmanager/api-ui/v1/releases/smtools-windows-x64.msi/download -H "x-api-key:%SM_API_KEY%" -o smtools-windows-x64.msi
          msiexec /i smtools-windows-x64.msi /quiet /qn

      - name: Set variables
        shell: bash
        id: variables
        run: |
          echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH
          echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" >> $GITHUB_PATH
          echo "C:\Program Files\DigiCert\DigiCert One Signing Manager Tools" >> $GITHUB_PATH

      - name: Use ssm-code-signing as before (or any other action that transitively uses ssm-code-signing)
        uses: digicert/ssm-code-signing@v0.0.2
...
```

It looks to me like this action isn't actually doing much more than installing some tools, so I will probably remove it from my workflow.
Still missing for me: the installation steps on Linux.

**Comment by floitsch** [comment]
According to Tech Support this issue should be fixed.

I have since migrated away from this action, but maybe someone else here could try it out and (if it works) close the issue.

**Comment by sduthil** [comment]
I can confirm that we had the same issue yesterday, and using the action works correctly now. Issue can be closed.

**Comment by duaneking** [comment]
This issue is persistent and inconsistent
